# Generated by Django 3.2.13 on 2023-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/gregcotech007/image/upload/v1677706290/media/profile_images/no_image.jpeg', upload_to='profile_images'),
        ),
    ]
